name: DefaultTamer
options:
  bundleIdPrefix: com.defaulttamer
  deploymentTarget:
    macOS: 13.0
packages:
  SQLite:
    url: https://github.com/stephencelis/SQLite.swift
    from: 0.15.3
  Sparkle:
    url: https://github.com/sparkle-project/Sparkle
    from: 2.6.0
targets:
  DefaultTamer:
    type: application
    platform: macOS
    deploymentTarget: 13.0
    info:
      path: DefaultTamer/Info.plist
      properties:
        CFBundleIdentifier: com.defaulttamer.app
        CFBundleName: $(PRODUCT_NAME)
        CFBundleShortVersionString: "$(MARKETING_VERSION)"
        CFBundleVersion: "$(CURRENT_PROJECT_VERSION)"
        LSMinimumSystemVersion: $(MACOSX_DEPLOYMENT_TARGET)
        LSUIElement: true
        CFBundleSignature: "DfTm"
        NSUserActivityTypes:
          - NSUserActivityTypeBrowsingWeb
        NSHighResolutionCapable: true
        SUFeedURL: https://www.defaulttamer.app/appcast.xml
        SUEnableAutomaticChecks: true
        SUPublicEDKey: 9W8teKdnj8NLMfjgwZIy1jv/cR4SytXzdLyY8hRA5sY=
        DTBaseURL: "$(DT_BASE_URL)"
        DTPromoURL: "$(DT_PROMO_URL)"
        DTAnalyticsURL: "$(DT_ANALYTICS_URL)"
        DTAnalyticsWebsiteID: "$(DT_ANALYTICS_WEBSITE_ID)"
        DTFeedbackToken: "$(DT_FEEDBACK_TOKEN)"
        CFBundleDocumentTypes:
          - CFBundleTypeName: HTML Document
            CFBundleTypeRole: Viewer
            CFBundleTypeExtensions:
              - html
              - htm
              - shtml
              - xhtml
              - shtm
              - xhtm
        CFBundleURLTypes:
          - CFBundleURLName: HTTP
            CFBundleURLSchemes:
              - http
          - CFBundleURLName: HTTPS
            CFBundleURLSchemes:
              - https
          - CFBundleURLName: Default Tamer Auth
            CFBundleURLSchemes:
              - defaulttamer
    sources:
      - DefaultTamer
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.defaulttamer.app
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        MACOSX_DEPLOYMENT_TARGET: 13.0
        SWIFT_VERSION: 5.9
        ENABLE_HARDENED_RUNTIME: YES
        COMBINE_HIDPI_IMAGES: YES
        CODE_SIGN_ENTITLEMENTS: DefaultTamer/DefaultTamer.entitlements
        DEVELOPMENT_TEAM: BZ2JB93F6F
        CODE_SIGNING_REQUIRED: YES
        CODE_SIGNING_ALLOWED: YES
        MARKETING_VERSION: "0.0.1"
        CURRENT_PROJECT_VERSION: "1"
        DT_BASE_URL: "https://www.defaulttamer.app"
        DT_PROMO_URL: "https://www.defaulttamer.app/promo.json"
        DT_ANALYTICS_URL: "https://analytics.0xlabs.space"
        DT_ANALYTICS_WEBSITE_ID: "babc74c5-5c94-4f0b-9a47-6b0b0fa12384"
        DT_FEEDBACK_TOKEN: "2f70a7b331d693fc3b61ad69ca0dcd6b10a30483a7bfffa5b3753cea0eb511d8"
      configs:
        Debug:
          CODE_SIGN_IDENTITY: "Apple Development"
          CODE_SIGN_STYLE: Automatic
          DT_BASE_URL: "http://localhost:4321"
          DT_PROMO_URL: "http://localhost:4321/promo.json"
          DT_FEEDBACK_TOKEN: "e31470b50d73ca656538332fc32f500dd93d809f48423699bb8cc8adbe84d291"
        Release:
          CODE_SIGN_IDENTITY: "Developer ID Application"
          CODE_SIGN_STYLE: Manual
    dependencies:
      - package: SQLite
        product: SQLite
      - package: Sparkle
        product: Sparkle
  DefaultTamerTests:
    type: bundle.unit-test
    platform: macOS
    deploymentTarget: 13.0
    sources:
      - DefaultTamerTests
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.defaulttamer.app.tests
      SWIFT_VERSION: 5.9
      GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: DefaultTamer
      - package: SQLite
        product: SQLite
